### ISSUE TITLE
Most recent data

### ISSUE THREAD

**Issue by petulla** [postandcourier/sc-candidate-visits#11]
hi there

I'm wondering if you have plans to update the dataset again soon. Thank you!

**Comment by jemory** [comment]
Yes. My apologies. It appears the script that was responsible to for updating this repo broke and I didn't notice. I'm working today to manually bring it back up to date.

**Comment by jemory** [comment]
Data are now current. I double checked data for Hillary and Sanders and they really haven't been to SC very much this month.

**Comment by lauragaton** [comment]
You can take me off these :)

Sent from my Verizon Wireless 4G LTE smartphone-------- Original message --------From: J Emory Parker notifications@github.com Date: 2/18/2016  2:15 PM  (GMT-05:00) To: postandcourier/sc-candidate-visits sc-candidate-visits@noreply.github.com Subject: Re: [sc-candidate-visits] Most recent data (#11) 
Closed #11.
